services:
  portuguesenewsaggregator:
    image: portuguesenewsaggregator
    restart: always
    build:
      context: .
      dockerfile: Worker/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Production
    volumes:
      - ./Worker/appsettings.json:/app/appsettings.json
      - ./Worker/appsettings.Development.json:/app/appsettings.Development.json
      - ./Worker/appsettings.Production.json:/app/appsettings.Production.json
    stdin_open: true
    tty: true
    depends_on:
      - mongo
      - mongo-express
    networks:
      mynetwork:
        ipv4_address: 178.25.0.3
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db # Persist mongo data
    networks:
      mynetwork:
        ipv4_address: 178.25.0.2
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 178.25.0.0/24

volumes:
  mongo-data: # Persistent storage for mongo data
