services:
  portuguesenewsaggregator:
    image: portuguesenewsaggregator
    restart: always
    build:
      context: .
      dockerfile: Worker/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Production
    volumes:
      - ./Worker/appsettings.json:/app/appsettings.json
      - ./Worker/appsettings.Development.json:/app/appsettings.Development.json
      - ./Worker/appsettings.Production.json:/app/appsettings.Production.json
    stdin_open: true
    tty: true
    networks:
      mynetwork:
        ipv4_address: 178.25.0.3

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 178.25.0.0/24
